### ISSUE TITLE
 Media queries nesten en werken met min-width

### ISSUE THREAD

**Issue by julia-stevens** [halima98/the-startup-active-collective#3]
Er staan nu allemaal verschillende media queries, maar je zou deze ook kunnen nesten. 
https://github.com/halima98/the-startup-active-collective/blob/2148099c8ab081cfd1398632caf3266778d6791b/styles.css#L1-L14

Je zou dit dus kunnen herschrijven als, onderstaande code. Let ook op dat je min-width gebruikt en niet max-width, want mobile first. 

```css
  .job_listings[data-per_page="3"] {
   @media screen and (min-width: ...px) {
         min-height: ...px;
    }

   @media screen and (min-width: ...px) {
         min-height: ...px;
    }

   @media screen and (min-width: ...px) {
         min-height: ...px;
   }
 }
```
